env:
  browser: true
  node: true
  amd: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  indent:
    - error
    - 4
    - { 'SwitchCase': 1 }
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
globals:
  django: true
  $: true
  $R: true
