fail_fast: true
exclude: "^docs/|/migrations/"
default_stages: [commit]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: debug-statements
  - id: check-added-large-files

- repo: https://github.com/commitizen-tools/commitizen
  rev: 3.5.2
  hooks:
  - id: commitizen
    stages: [commit-msg]

- repo: https://github.com/asottile/pyupgrade
  rev: "v3.8.0"
  hooks:
  - id: pyupgrade
    args: [--py310-plus]

- repo: https://github.com/adamchainz/django-upgrade
  rev: "1.14.0"
  hooks:
  - id: django-upgrade
    args: [--target-version, "4.2"]

- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.32.0
  hooks:
  - id: yapf
    additional_dependencies: [toml]
    args:
    - --parallel
    - --in-place
    exclude: ^.*\b(migrations)\b.*$

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.277
  hooks:
    - id: ruff
