[tool.ruff]
target-version = "py310"
fix = true
format = "text"
line-length = 100
select = [
    "E",
    "F",
    "W",
    "B",
    "I",
    "UP",
    "N",
    "B",
    "A",
    "C4",
    "ISC",
    "ICN",
    "T20",
    "C90",
    "PT",
    "Q",
    "RET",
    "SIM",
    "TID",
    "ERA",
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    "PIE",
    "RUF",
]

extend-ignore = ["A003", "RUF005", "N999", "RUF012"]

exclude = [
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    "build",
    "dist",
    "node_modules",
    "migrations",
]

[tool.ruff.isort]
combine-as-imports = true
force-single-line = false

[tool.ruff.pylint]
allow-magic-value-types = ["int", "str", "bytes"]

[tool.isort]
profile = "black"
line_length = 100
atomic = true
skip = "migrations"

[tool.ruff.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "single"
docstring-quotes = "double"
avoid-escape = true

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "app.settings"
norecursedirs = "assets static uploads .git node_modules htmlcov .tox .cache .pnpm-store"
python_files = "tests.py *_tests.py"
addopts = "--maxfail=1 -rf -s --nomigrations --cov=. --cov-report=html --cov-report=term:skip-covered --numprocesses=auto"

[tool.yapfignore]
ignore_patterns = ["**/migrations/*.py"]

[tool.yapf]
based_on_style = "pep8"
dedent_closing_brackets = true
coalesce_brackets = false
allow_split_before_dict_value = false
column_limit = 100
split_before_dot = false
split_all_top_level_comma_separated_values = true
spaces_around_tuple_delimiters = false
space_between_ending_comma_and_closing_bracket = false
blank_line_before_nested_class_or_def = false
align_closing_bracket_with_visual_indent = true
split_before_first_argument = false
split_before_expression_after_opening_paren = true
